services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "28017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  python_client:
    image: python:3.9-slim
    container_name: python_client
    depends_on:
      - mongodb
    volumes:
      - /home/moi1:/usr/src/app
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]
    environment:
     MONGO_URI: "mongodb://root:example@mongodb:27017/"

volumes:
  mongodata:
